#include "deck.h"

const card_s g_cards[52] = {
    { .color = "heart  ", .name = "ace  ", .value = 11 },
    { .color = "heart  ", .name = "two  ", .value = 2 },
    { .color = "heart  ", .name = "three", .value = 3 },
    { .color = "heart  ", .name = "four ", .value = 4 },
    { .color = "heart  ", .name = "five ", .value = 5 },
    { .color = "heart  ", .name = "six  ", .value = 6 },
    { .color = "heart  ", .name = "seven", .value = 7 },
    { .color = "heart  ", .name = "eight", .value = 8 },
    { .color = "heart  ", .name = "nine ", .value = 9 },
    { .color = "heart  ", .name = "ten  ", .value = 10 },
    { .color = "heart  ", .name = "jack ", .value = 10 },
    { .color = "heart  ", .name = "queen", .value = 10 },
    { .color = "heart  ", .name = "king ", .value = 10 },

    { .color = "spade  ", .name = "ace  ", .value = 11 },
    { .color = "spade  ", .name = "two  ", .value = 2 },
    { .color = "spade  ", .name = "three", .value = 3 },
    { .color = "spade  ", .name = "four ", .value = 4 },
    { .color = "spade  ", .name = "five ", .value = 5 },
    { .color = "spade  ", .name = "six  ", .value = 6 },
    { .color = "spade  ", .name = "seven", .value = 7 },
    { .color = "spade  ", .name = "eight", .value = 8 },
    { .color = "spade  ", .name = "nine ", .value = 9 },
    { .color = "spade  ", .name = "ten  ", .value = 10 },
    { .color = "spade  ", .name = "jack ", .value = 10 },
    { .color = "spade  ", .name = "queen", .value = 10 },
    { .color = "spade  ", .name = "king ", .value = 10 },

    { .color = "club   ", .name = "ace  ", .value = 11 },
    { .color = "club   ", .name = "two  ", .value = 2 },
    { .color = "club   ", .name = "three", .value = 3 },
    { .color = "club   ", .name = "four ", .value = 4 },
    { .color = "club   ", .name = "five ", .value = 5 },
    { .color = "club   ", .name = "six  ", .value = 6 },
    { .color = "club   ", .name = "seven", .value = 7 },
    { .color = "club   ", .name = "eight", .value = 8 },
    { .color = "club   ", .name = "nine ", .value = 9 },
    { .color = "club   ", .name = "ten  ", .value = 10 },
    { .color = "club   ", .name = "jack ", .value = 10 },
    { .color = "club   ", .name = "queen", .value = 10 },
    { .color = "club   ", .name = "king ", .value = 10 },

    { .color = "diamond", .name = "ace  ", .value = 11 },
    { .color = "diamond", .name = "two  ", .value = 2 },
    { .color = "diamond", .name = "three", .value = 3 },
    { .color = "diamond", .name = "four ", .value = 4 },
    { .color = "diamond", .name = "five ", .value = 5 },
    { .color = "diamond", .name = "six  ", .value = 6 },
    { .color = "diamond", .name = "seven", .value = 7 },
    { .color = "diamond", .name = "eight", .value = 8 },
    { .color = "diamond", .name = "nine ", .value = 9 },
    { .color = "diamond", .name = "ten  ", .value = 10 },
    { .color = "diamond", .name = "jack ", .value = 10 },
    { .color = "diamond", .name = "queen", .value = 10 },
    { .color = "diamond", .name = "king ", .value = 10 }
};
