#include "deck.h"

const deck_s  DECK = {
    .cards[0] = { .color = "heart  ", .name = "ace  ", .value = 11 },
    .cards[1] = { .color = "heart  ", .name = "two  ", .value = 2 },
    .cards[2] = { .color = "heart  ", .name = "three", .value = 3 },
    .cards[3] = { .color = "heart  ", .name = "four ", .value = 4 },
    .cards[4] = { .color = "heart  ", .name = "five ", .value = 5 },
    .cards[5] = { .color = "heart  ", .name = "six  ", .value = 6 },
    .cards[6] = { .color = "heart  ", .name = "seven", .value = 7 },
    .cards[7] = { .color = "heart  ", .name = "eight", .value = 8 },
    .cards[8] = { .color = "heart  ", .name = "nine ", .value = 9 },
    .cards[9] = { .color = "heart  ", .name = "ten  ", .value = 10 },
    .cards[10] = { .color = "heart  ", .name = "jack ", .value = 10 },
    .cards[11] = { .color = "heart  ", .name = "queen", .value = 10 },
    .cards[12] = { .color = "heart  ", .name = "king ", .value = 10 },

    .cards[13] = { .color = "spade  ", .name = "ace  ", .value = 11 },
    .cards[14] = { .color = "spade  ", .name = "two  ", .value = 2 },
    .cards[15] = { .color = "spade  ", .name = "three", .value = 3 },
    .cards[16] = { .color = "spade  ", .name = "four ", .value = 4 },
    .cards[17] = { .color = "spade  ", .name = "five ", .value = 5 },
    .cards[18] = { .color = "spade  ", .name = "six  ", .value = 6 },
    .cards[19] = { .color = "spade  ", .name = "seven", .value = 7 },
    .cards[20] = { .color = "spade  ", .name = "eight", .value = 8 },
    .cards[21] = { .color = "spade  ", .name = "nine ", .value = 9 },
    .cards[22] = { .color = "spade  ", .name = "ten  ", .value = 10 },
    .cards[23] = { .color = "spade  ", .name = "jack ", .value = 10 },
    .cards[24] = { .color = "spade  ", .name = "queen", .value = 10 },
    .cards[25] = { .color = "spade  ", .name = "king ", .value = 10 },

    .cards[26] = { .color = "club   ", .name = "ace  ", .value = 11 },
    .cards[27] = { .color = "club   ", .name = "two  ", .value = 2 },
    .cards[28] = { .color = "club   ", .name = "three", .value = 3 },
    .cards[29] = { .color = "club   ", .name = "four ", .value = 4 },
    .cards[30] = { .color = "club   ", .name = "five ", .value = 5 },
    .cards[31] = { .color = "club   ", .name = "six  ", .value = 6 },
    .cards[32] = { .color = "club   ", .name = "seven", .value = 7 },
    .cards[33] = { .color = "club   ", .name = "eight", .value = 8 },
    .cards[34] = { .color = "club   ", .name = "nine ", .value = 9 },
    .cards[35] = { .color = "club   ", .name = "ten  ", .value = 10 },
    .cards[36] = { .color = "club   ", .name = "jack ", .value = 10 },
    .cards[37] = { .color = "club   ", .name = "queen", .value = 10 },
    .cards[38] = { .color = "club   ", .name = "king ", .value = 10 },

    .cards[39] = { .color = "diamond", .name = "ace  ", .value = 11 },
    .cards[40] = { .color = "diamond", .name = "two  ", .value = 2 },
    .cards[41] = { .color = "diamond", .name = "three", .value = 3 },
    .cards[42] = { .color = "diamond", .name = "four ", .value = 4 },
    .cards[43] = { .color = "diamond", .name = "five ", .value = 5 },
    .cards[44] = { .color = "diamond", .name = "six  ", .value = 6 },
    .cards[45] = { .color = "diamond", .name = "seven", .value = 7 },
    .cards[46] = { .color = "diamond", .name = "eight", .value = 8 },
    .cards[47] = { .color = "diamond", .name = "nine ", .value = 9 },
    .cards[48] = { .color = "diamond", .name = "ten  ", .value = 10 },
    .cards[49] = { .color = "diamond", .name = "jack ", .value = 10 },
    .cards[50] = { .color = "diamond", .name = "queen", .value = 10 },
    .cards[51] = { .color = "diamond", .name = "king ", .value = 10 }
};
